--- #YAML:1.0
name:               Plack-Middleware-Session-Fixation
version:            0.01
abstract:           Plack::Middleware::Session + fixation block
author:
    - Shinichiro Aska <s.aska.org@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
    version:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
